# Generated by Django 4.2.21 on 2026-06-17 10:15

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Category name (letters, numbers, spaces, hyphens, ampersands).', max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Category name may only contain letters, numbers, spaces, hyphens, and ampersands.', regex='^[a-zA-Z0-9\\s\\-&]{1,50}$')])),
                ('description', models.TextField(blank=True, help_text='Optional category description.', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'inventory_category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Item name.', max_length=100, validators=[django.core.validators.RegexValidator(message='Item name may only contain letters, numbers, spaces, hyphens, dots, commas, parentheses, ampersands, and apostrophes.', regex="^[a-zA-Z0-9\\s\\-\\.,()&']{1,100}$")])),
                ('description', models.TextField(blank=True, help_text='Optional item description (max 1000 characters).', max_length=1000)),
                ('quantity', models.PositiveIntegerField(default=0, help_text='Current stock quantity (0-999,999).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)])),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Item price (0.00-9,999,999.99).', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('9999999.99'))])),
                ('sku', models.CharField(blank=True, help_text='Optional Stock Keeping Unit code (uppercase alphanumeric + hyphens).', max_length=50, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='SKU may only contain uppercase letters, digits, and hyphens.', regex='^[A-Z0-9\\-]{1,50}$')])),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('OUT_OF_STOCK', 'Out of Stock')], default='ACTIVE', help_text='Item availability status.', max_length=20)),
                ('image', models.ImageField(blank=True, help_text='Optional item image (jpg, jpeg, png, gif).', null=True, upload_to='inventory/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, help_text='Optional item category.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='inventory_service.category')),
                ('owner', models.ForeignKey(help_text='User who owns this inventory item.', on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inventory Item',
                'verbose_name_plural': 'Inventory Items',
                'db_table': 'inventory_item',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_name_snapshot', models.CharField(blank=True, help_text='Item name at the time of the event (preserved if item is deleted).', max_length=100)),
                ('username_snapshot', models.CharField(blank=True, help_text='Username at the time of the event.', max_length=150)),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('DELETED', 'Deleted'), ('VIEWED', 'Viewed')], help_text='Type of action performed.', max_length=20)),
                ('field_changed', models.CharField(blank=True, help_text='Name of the field that was changed (for UPDATED events).', max_length=100)),
                ('old_value', models.TextField(blank=True, help_text='Previous value before the change.')),
                ('new_value', models.TextField(blank=True, help_text='New value after the change.')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Client IP address at the time of the event.', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(blank=True, help_text='Item that was acted upon.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='inventory_service.inventoryitem')),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the action.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inventory Audit Log',
                'verbose_name_plural': 'Inventory Audit Logs',
                'db_table': 'inventory_audit_log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['owner', 'status'], name='inv_item_owner_status_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['category'], name='inv_item_category_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['sku'], name='inv_item_sku_idx'),
        ),
    ]
