# Generated by Django 4.2.21 on 2026-06-17 10:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, help_text='Username snapshot at the time of the event.', max_length=150)),
                ('action', models.CharField(choices=[('USER_REGISTERED', 'User Registered'), ('USER_LOGIN', 'User Login'), ('USER_LOGOUT', 'User Logout'), ('PASSWORD_CHANGED', 'Password Changed'), ('PASSWORD_RESET_REQUESTED', 'Password Reset Requested'), ('LOGIN_FAILED', 'Login Failed'), ('PROFILE_UPDATED', 'Profile Updated'), ('INVENTORY_CREATED', 'Inventory Created'), ('INVENTORY_UPDATED', 'Inventory Updated'), ('INVENTORY_DELETED', 'Inventory Deleted'), ('INVENTORY_VIEWED', 'Inventory Viewed'), ('ACCESS_DENIED', 'Access Denied'), ('IDOR_ATTEMPT', 'IDOR Attempt'), ('USER_ROLE_CHANGED', 'User Role Changed'), ('USER_DEACTIVATED', 'User Deactivated'), ('USER_ACTIVATED', 'User Activated')], db_index=True, help_text='Type of action performed.', max_length=30)),
                ('service', models.CharField(db_index=True, help_text='Source microservice (auth_service, inventory_service, audit_service).', max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Client IP address at the time of the event.', null=True)),
                ('details', models.TextField(blank=True, help_text='Additional context. Must NOT contain passwords or tokens.', max_length=1000)),
                ('resource_type', models.CharField(blank=True, help_text="Type of resource acted upon (e.g., 'InventoryItem', 'User').", max_length=50)),
                ('resource_id', models.CharField(blank=True, help_text='ID of the resource acted upon.', max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the event was recorded.')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_log',
                'ordering': ['-timestamp'],
            },
        ),
    ]
