"""
Inventory Service models: Category, InventoryItem, InventoryAuditLog.

Security controls:
- UUID primary keys on all models to prevent ID enumeration / IDOR (OWASP A01)
- owner ForeignKey ties every item to a user; IDOR prevention enforced in views (OWASP A01)
- Regex validators on name/SKU/category fields (OWASP A03)
- Quantity and price bounds validation (OWASP A03)
- status auto-set to OUT_OF_STOCK when quantity reaches 0 (business logic safety)
- Image field uses UUID filename (generated in validators.py) (OWASP A04)
- All foreign keys use SET_NULL so audit records survive item/user deletion (OWASP A09)

Maps to:
- OWASP A01:2021 - Broken Access Control (UUID PKs, ownership)
- OWASP A03:2021 - Injection (input validation)
- OWASP A04:2021 - Insecure Design (file upload)
- OWASP A09:2021 - Security Logging and Monitoring Failures
- ASVS V4.2 - Operation Level Access Control
- ASVS V5.1 - Input Validation
- ASVS V12.1 - File Upload Requirements
"""

import uuid
import logging
from decimal import Decimal

from django.conf import settings
from django.core.validators import MinValueValidator, MaxValueValidator, RegexValidator
from django.db import models

logger = logging.getLogger("django")

# =============================================================================
# Validators
# =============================================================================

# Category name: alphanumeric + spaces, hyphens, ampersand (1-50 chars)
# Maps to OWASP A03:2021 - Injection
_category_name_validator = RegexValidator(
    regex=r"^[a-zA-Z0-9\s\-&]{1,50}$",
    message=(
        "Category name may only contain letters, numbers, spaces, "
        "hyphens, and ampersands."
    ),
)

# Item name: alphanumeric + common punctuation (1-100 chars)
# Maps to OWASP A03:2021 - Injection
_item_name_validator = RegexValidator(
    regex=r"^[a-zA-Z0-9\s\-\.,()&']{1,100}$",
    message=(
        "Item name may only contain letters, numbers, spaces, hyphens, "
        "dots, commas, parentheses, ampersands, and apostrophes."
    ),
)

# SKU: uppercase alphanumeric + hyphens (1-50 chars)
# Maps to OWASP A03:2021 - Injection
_sku_validator = RegexValidator(
    regex=r"^[A-Z0-9\-]{1,50}$",
    message="SKU may only contain uppercase letters, digits, and hyphens.",
)


# =============================================================================
# Category
# =============================================================================

class Category(models.Model):
    """
    Inventory category.

    Security: name is regex-validated to prevent injection.
    Maps to OWASP A03:2021 - Injection.
    """

    # UUID PK prevents sequential ID enumeration
    # Maps to OWASP A01:2021 - Broken Access Control
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False,
    )
    name = models.CharField(
        max_length=50,
        unique=True,
        validators=[_category_name_validator],
        help_text="Category name (letters, numbers, spaces, hyphens, ampersands).",
    )
    description = models.TextField(
        max_length=200,
        blank=True,
        help_text="Optional category description.",
    )
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = "inventory_category"
        ordering = ["name"]
        verbose_name = "Category"
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.name


# =============================================================================
# InventoryItem
# =============================================================================

class InventoryItem(models.Model):
    """
    A single inventory item owned by a user.

    Security features:
    - UUID PK: prevents IDOR via sequential integer IDs (OWASP A01)
    - owner FK: enforces row-level ownership; filtered in every queryset (OWASP A01)
    - Regex validators on name and SKU (OWASP A03)
    - Quantity/price bounds enforced at model layer (OWASP A03)
    - Image stored with UUID filename generated by validate_file_upload (OWASP A04)
    - status auto-corrected when quantity drops to 0

    Maps to:
    - OWASP A01:2021 - Broken Access Control (UUID PK, owner FK)
    - OWASP A03:2021 - Injection (validators)
    - OWASP A04:2021 - Insecure Design (file upload)
    - ASVS V4.2 - Operation Level Access Control
    - ASVS V5.1 - Input Validation
    """

    class Status(models.TextChoices):
        ACTIVE = "ACTIVE", "Active"
        INACTIVE = "INACTIVE", "Inactive"
        OUT_OF_STOCK = "OUT_OF_STOCK", "Out of Stock"

    # UUID PK prevents ID enumeration / IDOR
    # Maps to OWASP A01:2021 - Broken Access Control
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False,
    )

    # Every item belongs to exactly one user — enforced in views too (IDOR prevention)
    # Maps to OWASP A01:2021 - Broken Access Control
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="inventory_items",
        help_text="User who owns this inventory item.",
    )

    # Validated name
    name = models.CharField(
        max_length=100,
        validators=[_item_name_validator],
        help_text="Item name.",
    )

    description = models.TextField(
        max_length=1000,
        blank=True,
        help_text="Optional item description (max 1000 characters).",
    )

    category = models.ForeignKey(
        Category,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="items",
        help_text="Optional item category.",
    )

    # Bounded quantity
    quantity = models.PositiveIntegerField(
        default=0,
        validators=[
            MinValueValidator(0),
            MaxValueValidator(999_999),
        ],
        help_text="Current stock quantity (0-999,999).",
    )

    # Bounded price stored as Decimal to avoid float precision issues
    price = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        default=Decimal("0.00"),
        validators=[
            MinValueValidator(Decimal("0.00")),
            MaxValueValidator(Decimal("9999999.99")),
        ],
        help_text="Item price (0.00-9,999,999.99).",
    )

    # Optional SKU — unique when provided, null when omitted
    sku = models.CharField(
        max_length=50,
        blank=True,
        null=True,
        unique=True,
        validators=[_sku_validator],
        help_text="Optional Stock Keeping Unit code (uppercase alphanumeric + hyphens).",
    )

    status = models.CharField(
        max_length=20,
        choices=Status.choices,
        default=Status.ACTIVE,
        help_text="Item availability status.",
    )

    # Image stored under media/inventory/ with UUID filename (set in views/serializers)
    # Maps to OWASP A04:2021 - Insecure Design
    image = models.ImageField(
        upload_to="inventory/",
        blank=True,
        null=True,
        help_text="Optional item image (jpg, jpeg, png, gif).",
    )

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "inventory_item"
        ordering = ["-created_at"]
        verbose_name = "Inventory Item"
        verbose_name_plural = "Inventory Items"
        indexes = [
            models.Index(fields=["owner", "status"], name="inv_item_owner_status_idx"),
            models.Index(fields=["category"], name="inv_item_category_idx"),
            models.Index(fields=["sku"], name="inv_item_sku_idx"),
        ]

    def __str__(self):
        return f"{self.name} (owner: {self.owner_id})"

    def save(self, *args, **kwargs):
        # Auto-set status when stock hits 0 — prevents inconsistent state
        if self.quantity == 0 and self.status == self.Status.ACTIVE:
            self.status = self.Status.OUT_OF_STOCK
        super().save(*args, **kwargs)


# =============================================================================
# InventoryAuditLog
# =============================================================================

class InventoryAuditLog(models.Model):
    """
    Item-level audit trail recording who changed what and when.

    SET_NULL on foreign keys ensures audit records survive user/item deletion.
    The username snapshot captures the name at the time of the event.

    Maps to:
    - OWASP A09:2021 - Security Logging and Monitoring Failures
    - ASVS V1.2 - Architecture (audit trail)
    """

    class Action(models.TextChoices):
        CREATED = "CREATED", "Created"
        UPDATED = "UPDATED", "Updated"
        DELETED = "DELETED", "Deleted"
        VIEWED = "VIEWED", "Viewed"

    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False,
    )

    # SET_NULL so audit records survive item deletion
    item = models.ForeignKey(
        InventoryItem,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="audit_logs",
        help_text="Item that was acted upon.",
    )
    item_name_snapshot = models.CharField(
        max_length=100,
        blank=True,
        help_text="Item name at the time of the event (preserved if item is deleted).",
    )

    # SET_NULL so audit records survive user deletion
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="inventory_audit_logs",
        help_text="User who performed the action.",
    )
    username_snapshot = models.CharField(
        max_length=150,
        blank=True,
        help_text="Username at the time of the event.",
    )

    action = models.CharField(
        max_length=20,
        choices=Action.choices,
        help_text="Type of action performed.",
    )

    field_changed = models.CharField(
        max_length=100,
        blank=True,
        help_text="Name of the field that was changed (for UPDATED events).",
    )
    old_value = models.TextField(
        blank=True,
        help_text="Previous value before the change.",
    )
    new_value = models.TextField(
        blank=True,
        help_text="New value after the change.",
    )

    ip_address = models.GenericIPAddressField(
        null=True,
        blank=True,
        help_text="Client IP address at the time of the event.",
    )
    timestamp = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = "inventory_audit_log"
        ordering = ["-timestamp"]
        verbose_name = "Inventory Audit Log"
        verbose_name_plural = "Inventory Audit Logs"

    def __str__(self):
        return (
            f"[{self.timestamp:%Y-%m-%d %H:%M}] "
            f"{self.action} on '{self.item_name_snapshot}' "
            f"by {self.username_snapshot}"
        )

    def save(self, *args, **kwargs):
        # Capture snapshots on first save so records survive FK deletion
        if not self.username_snapshot and self.user:
            self.username_snapshot = self.user.username
        if not self.item_name_snapshot and self.item:
            self.item_name_snapshot = self.item.name
        super().save(*args, **kwargs)